### ISSUE TITLE
Impossible d'ajouter une entrée

### ISSUE THREAD

**Issue by FlachyJoe** [yeKcim/inventaire#2]
Bonjour,
j'essaie d'installer votre inventaire pour lister des composants éléctroniques.
J'ai suivi les instructions du README, créé une base "inventaire" avec le bouton + mais lorsque je clique sur le bouton bleu "Ajouter une nouvelle entrée" et quoi que je renseigne, j'obtiens un cadre blanc et ces messages dans le journal d'erreur :

```
[Wed Jan 19 11:23:17.482937 2022] [php:warn] [pid 685877] [client 127.0.0.1:36650] PHP Warning:  Undefined variable $i in /var/www/inventaire/add.php on line 222, referer: http://127.0.0.2/
[Wed Jan 19 11:23:17.484343 2022] [php:warn] [pid 685877] [client 127.0.0.1:36650] PHP Warning:  Undefined array key 0 in /var/www/inventaire/blocs/administratif.php on line 146, referer: http://127.0.0.2/
[Wed Jan 19 11:23:17.484365 2022] [php:warn] [pid 685877] [client 127.0.0.1:36650] PHP Warning:  Trying to access array offset on value of type null in /var/www/inventaire/blocs/administratif.php on line 146, referer: http://127.0.0.2/
>>>> Messages identiques pour les lignes 150, 157, 158, 159, 176, 188, 189, 190, 224, 225, 226, 241, 246, 252, 254, 261, 262, 263, 285, 289

[Wed Jan 19 11:23:17.485775 2022] [php:warn] [pid 685877] [client 127.0.0.1:36650] PHP Warning:  Undefined array key 0 in /var/www/inventaire/blocs/technique.php on line 216, referer: http://127.0.0.2/
[Wed Jan 19 11:23:17.485784 2022] [php:warn] [pid 685877] [client 127.0.0.1:36650] PHP Warning:  Trying to access array offset on value of type null in /var/www/inventaire/blocs/technique.php on line 216, referer: http://127.0.0.2/
>>>> Messages identiques pour les lignes 217, 218, 230, 241, 246, 281, 283, 297, 301

[Wed Jan 19 11:23:19.328084 2022] [php:error] [pid 685877] [client 127.0.0.1:36650] PHP Fatal error:  Uncaught ValueError: max(): Argument #1 ($value) must contain at least one element in /var/www/inventaire/0_fonctions.php:289\nStack trace:\n#0 /var/www/inventaire/0_fonctions.php(289): max()\n#1 /var/www/inventaire/add.php(176): new_lab_id()\n#2 {main}\n  thrown in /var/www/inventaire/0_fonctions.php on line 289, referer: http://127.0.0.2/add.php?BASE=inventaire
[Wed Jan 19 11:23:20.662528 2022] [php:error] [pid 685877] [client 127.0.0.1:36650] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') GROUP BY historique_id ORDER BY historique_id ASC' at line 1 in /var/www/inventaire/0_listing.php:44\nStack trace:\n#0 /var/www/inventaire/0_listing.php(44): PDO->query()\n#1 /var/www/inventaire/index.php(42): require_once('...')\n#2 {main}\n  thrown in /var/www/inventaire/0_listing.php on line 44
[Wed Jan 19 11:23:21.792254 2022] [php:warn] [pid 685877] [client 127.0.0.1:36650] PHP Warning:  Undefined variable $i in /var/www/inventaire/add.php on line 222, referer: http://127.0.0.2/

[Wed Jan 19 11:23:37.958901 2022] [php:warn] [pid 683541] [client 127.0.0.1:36658] PHP Warning:  Undefined array key 0 in /var/www/inventaire/0_fonctions.php on line 300, referer: http://127.0.0.2/add.php?BASE=inventaire
[Wed Jan 19 11:23:37.958922 2022] [php:warn] [pid 683541] [client 127.0.0.1:36658] PHP Warning:  Trying to access array offset on value of type null in /var/www/inventaire/0_fonctions.php on line 300, referer: http://127.0.0.2/add.php?BASE=inventaire
[Wed Jan 19 11:23:37.959074 2022] [php:error] [pid 683541] [client 127.0.0.1:36658] PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'serial_number' cannot be null in /var/www/inventaire/add.php:190\nStack trace:\n#0 /var/www/inventaire/add.php(190): PDO->query()\n#1 {main}\n  thrown in /var/www/inventaire/add.php on line 190, referer: http://127.0.0.2/add.php?BASE=inventaire
[Wed Jan 19 11:23:40.366996 2022] [php:error] [pid 683541] [client 127.0.0.1:36658] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') GROUP BY historique_id ORDER BY historique_id ASC' at line 1 in /var/www/inventaire/0_listing.php:44\nStack trace:\n#0 /var/www/inventaire/0_listing.php(44): PDO->query()\n#1 /var/www/inventaire/index.php(42): require_once('...')\n#2 {main}\n  thrown in /var/www/inventaire/0_listing.php on line 44

```
N'y aurait-il pas des valeurs à rentrer dans la base pour l'initialiser ? Ou des tests manquant dans le code pour le cas d'une base vide ?

**Comment by yeKcim** [comment]
Il y a 3 ans, l’installation fonctionnait directement mais depuis une version récente de php, je rencontre quelques problèmes. Je résous les bugs pour l’utilisation mais je ne l’ai pas installé from scratch depuis quelques temps. En effet, il semble y avoir "quelques" erreurs. Je vais tenter de regarder ça dès que je trouve un peu de temps, merci pour le retour

**Comment by yeKcim** [comment]
Normalement le bug en question est résolu. Merci pour le signalement.

**Comment by FlachyJoe** [comment]
Bonjour,
J'obtiens maintenant le message 

> L’entrée a été ajoutée à la base de donnée.
> Vous pouvez directement ajouter une nouvelle entrée
> ou [→ Compléter les informations de mach1 #1](http://127.0.0.2/info.php?BASE=inventaire&i=1)

mais l'item n'est ajouté dans la base (c'est ok pour une nouvelle catégorie par contre) et j'ai encore ces erreurs dans le journal
```
[Tue Feb 08 10:21:04.128633 2022] [php:error] [pid 411600] [client 127.0.0.1:55172] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 2014 Cannot execute queries while there are pending result sets. Consider unsetting the previous PDOStatement or calling PDOStatement::closeCursor() in /var/www/inventaire/blocs/administratif.php:23\nStack trace:\n#0 /var/www/inventaire/blocs/administratif.php(23): PDO->query()\n#1 /var/www/inventaire/add.php(262): require_once('...')\n#2 {main}\n  thrown in /var/www/inventaire/blocs/administratif.php on line 23, referer: http://127.0.0.2/add.php?BASE=inventaire
[Tue Feb 08 10:21:17.936538 2022] [php:error] [pid 1286] [client 127.0.0.1:55174] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') GROUP BY historique_id ORDER BY historique_id ASC' at line 1 in /var/www/inventaire/0_listing.php:44\nStack trace:\n#0 /var/www/inventaire/0_listing.php(44): PDO->query()\n#1 /var/www/inventaire/index.php(42): require_once('...')\n#2 {main}\n  thrown in /var/www/inventaire/0_listing.php on line 44, referer: http://127.0.0.2/?BASE=inventaire
[Tue Feb 08 10:21:20.319631 2022] [php:error] [pid 1286] [client 127.0.0.1:55174] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') GROUP BY historique_id ORDER BY historique_id ASC' at line 1 in /var/www/inventaire/0_listing.php:44\nStack trace:\n#0 /var/www/inventaire/0_listing.php(44): PDO->query()\n#1 /var/www/inventaire/index.php(42): require_once('...')\n#2 {main}\n  thrown in /var/www/inventaire/0_listing.php on line 44, referer: http://127.0.0.2/?BASE=inventaire
[Tue Feb 08 10:21:21.287981 2022] [php:error] [pid 1286] [client 127.0.0.1:55174] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') GROUP BY historique_id ORDER BY historique_id ASC' at line 1 in /var/www/inventaire/0_listing.php:44\nStack trace:\n#0 /var/www/inventaire/0_listing.php(44): PDO->query()\n#1 /var/www/inventaire/index.php(42): require_once('...')\n#2 {main}\n  thrown in /var/www/inventaire/0_listing.php on line 44, referer: http://127.0.0.2/?BASE=inventaire
[Tue Feb 08 10:23:33.500011 2022] [php:error] [pid 411600] [client 127.0.0.1:55192] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 2014 Cannot execute queries while there are pending result sets. Consider unsetting the previous PDOStatement or calling PDOStatement::closeCursor() in /var/www/inventaire/blocs/administratif.php:23\nStack trace:\n#0 /var/www/inventaire/blocs/administratif.php(23): PDO->query()\n#1 /var/www/inventaire/add.php(262): require_once('...')\n#2 {main}\n  thrown in /var/www/inventaire/blocs/administratif.php on line 23, referer: http://127.0.0.2/add.php?BASE=inventaire
[Tue Feb 08 10:23:36.359462 2022] [php:error] [pid 411600] [client 127.0.0.1:55192] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') GROUP BY historique_id ORDER BY historique_id ASC' at line 1 in /var/www/inventaire/0_listing.php:44\nStack trace:\n#0 /var/www/inventaire/0_listing.php(44): PDO->query()\n#1 /var/www/inventaire/index.php(42): require_once('...')\n#2 {main}\n  thrown in /var/www/inventaire/0_listing.php on line 44, referer: http://127.0.0.2/?BASE=inventaire
[Tue Feb 08 10:23:38.583773 2022] [php:error] [pid 411600] [client 127.0.0.1:55192] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') GROUP BY historique_id ORDER BY historique_id ASC' at line 1 in /var/www/inventaire/0_listing.php:44\nStack trace:\n#0 /var/www/inventaire/0_listing.php(44): PDO->query()\n#1 /var/www/inventaire/index.php(42): require_once('...')\n#2 {main}\n  thrown in /var/www/inventaire/0_listing.php on line 44, referer: http://127.0.0.2/?BASE=inventaire
[Tue Feb 08 10:25:18.906390 2022] [php:error] [pid 1286] [client 127.0.0.1:55204] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 2014 Cannot execute queries while there are pending result sets. Consider unsetting the previous PDOStatement or calling PDOStatement::closeCursor() in /var/www/inventaire/blocs/administratif.php:23\nStack trace:\n#0 /var/www/inventaire/blocs/administratif.php(23): PDO->query()\n#1 /var/www/inventaire/add.php(262): require_once('...')\n#2 {main}\n  thrown in /var/www/inventaire/blocs/administratif.php on line 23, referer: http://127.0.0.2/add.php?BASE=inventaire
```

EDIT : il a aussi fallu que je crée un dossier 'files' dont l'absence provoquait une erreur.

**Comment by yeKcim** [comment]
Oui, j’aurais dû préciser, j’ai résolu ce bug spécifique mais il reste encore pas mal de taf pour tout rendre nickel (remplacer x-moz-errormessage, plusieurs autres problèmes également, en particulier sur les select).

Pour la création du dossier files, j’étais justement en train de bosser dessus ce matin. J’ai vu l’erreur hier soir mais j’avais l’impression que c’était dû au fait que $racine était mal renseigné dans mon fichier de config (ce qui n’empêche qu’un message d’erreur devrait être affiché)

Je vais également regarder pour les erreurs que vous rapportez ici

**Comment by yeKcim** [comment]
Beaucoup de changements depuis votre essai. Désolé pour l’absence de réponse, je ne maintenais plus le dépôt et je pensais ne plus maintenir ce code mais je viens de le ressuscité pour mon propre usage. Je suppose que depuis le temps, vous avez trouvé un autre outil pour répondre à votre besoin…
